/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ResetPasswordRequestService } from "../resetPasswordRequest.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ResetPasswordRequestCreateInput } from "./ResetPasswordRequestCreateInput";
import { ResetPasswordRequest } from "./ResetPasswordRequest";
import { ResetPasswordRequestFindManyArgs } from "./ResetPasswordRequestFindManyArgs";
import { ResetPasswordRequestWhereUniqueInput } from "./ResetPasswordRequestWhereUniqueInput";
import { ResetPasswordRequestUpdateInput } from "./ResetPasswordRequestUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ResetPasswordRequestControllerBase {
  constructor(
    protected readonly service: ResetPasswordRequestService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ResetPasswordRequest })
  @nestAccessControl.UseRoles({
    resource: "ResetPasswordRequest",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createResetPasswordRequest(
    @common.Body() data: ResetPasswordRequestCreateInput
  ): Promise<ResetPasswordRequest> {
    return await this.service.createResetPasswordRequest({
      data: data,
      select: {
        createdAt: true,
        email: true,
        expires: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ResetPasswordRequest] })
  @ApiNestedQuery(ResetPasswordRequestFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ResetPasswordRequest",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async resetPasswordRequests(
    @common.Req() request: Request
  ): Promise<ResetPasswordRequest[]> {
    const args = plainToClass(ResetPasswordRequestFindManyArgs, request.query);
    return this.service.resetPasswordRequests({
      ...args,
      select: {
        createdAt: true,
        email: true,
        expires: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ResetPasswordRequest })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ResetPasswordRequest",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async resetPasswordRequest(
    @common.Param() params: ResetPasswordRequestWhereUniqueInput
  ): Promise<ResetPasswordRequest | null> {
    const result = await this.service.resetPasswordRequest({
      where: params,
      select: {
        createdAt: true,
        email: true,
        expires: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ResetPasswordRequest })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ResetPasswordRequest",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateResetPasswordRequest(
    @common.Param() params: ResetPasswordRequestWhereUniqueInput,
    @common.Body() data: ResetPasswordRequestUpdateInput
  ): Promise<ResetPasswordRequest | null> {
    try {
      return await this.service.updateResetPasswordRequest({
        where: params,
        data: data,
        select: {
          createdAt: true,
          email: true,
          expires: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ResetPasswordRequest })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ResetPasswordRequest",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteResetPasswordRequest(
    @common.Param() params: ResetPasswordRequestWhereUniqueInput
  ): Promise<ResetPasswordRequest | null> {
    try {
      return await this.service.deleteResetPasswordRequest({
        where: params,
        select: {
          createdAt: true,
          email: true,
          expires: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
