/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ReminderMailService } from "../reminderMail.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ReminderMailCreateInput } from "./ReminderMailCreateInput";
import { ReminderMail } from "./ReminderMail";
import { ReminderMailFindManyArgs } from "./ReminderMailFindManyArgs";
import { ReminderMailWhereUniqueInput } from "./ReminderMailWhereUniqueInput";
import { ReminderMailUpdateInput } from "./ReminderMailUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ReminderMailControllerBase {
  constructor(
    protected readonly service: ReminderMailService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ReminderMail })
  @nestAccessControl.UseRoles({
    resource: "ReminderMail",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createReminderMail(
    @common.Body() data: ReminderMailCreateInput
  ): Promise<ReminderMail> {
    return await this.service.createReminderMail({
      data: data,
      select: {
        createdAt: true,
        elapsedMinutes: true,
        id: true,
        referenceId: true,
        reminderType: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ReminderMail] })
  @ApiNestedQuery(ReminderMailFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ReminderMail",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async reminderMails(@common.Req() request: Request): Promise<ReminderMail[]> {
    const args = plainToClass(ReminderMailFindManyArgs, request.query);
    return this.service.reminderMails({
      ...args,
      select: {
        createdAt: true,
        elapsedMinutes: true,
        id: true,
        referenceId: true,
        reminderType: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ReminderMail })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ReminderMail",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async reminderMail(
    @common.Param() params: ReminderMailWhereUniqueInput
  ): Promise<ReminderMail | null> {
    const result = await this.service.reminderMail({
      where: params,
      select: {
        createdAt: true,
        elapsedMinutes: true,
        id: true,
        referenceId: true,
        reminderType: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ReminderMail })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ReminderMail",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateReminderMail(
    @common.Param() params: ReminderMailWhereUniqueInput,
    @common.Body() data: ReminderMailUpdateInput
  ): Promise<ReminderMail | null> {
    try {
      return await this.service.updateReminderMail({
        where: params,
        data: data,
        select: {
          createdAt: true,
          elapsedMinutes: true,
          id: true,
          referenceId: true,
          reminderType: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ReminderMail })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ReminderMail",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteReminderMail(
    @common.Param() params: ReminderMailWhereUniqueInput
  ): Promise<ReminderMail | null> {
    try {
      return await this.service.deleteReminderMail({
        where: params,
        select: {
          createdAt: true,
          elapsedMinutes: true,
          id: true,
          referenceId: true,
          reminderType: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
