/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { ReminderMail } from "./ReminderMail";
import { ReminderMailCountArgs } from "./ReminderMailCountArgs";
import { ReminderMailFindManyArgs } from "./ReminderMailFindManyArgs";
import { ReminderMailFindUniqueArgs } from "./ReminderMailFindUniqueArgs";
import { CreateReminderMailArgs } from "./CreateReminderMailArgs";
import { UpdateReminderMailArgs } from "./UpdateReminderMailArgs";
import { DeleteReminderMailArgs } from "./DeleteReminderMailArgs";
import { ReminderMailService } from "../reminderMail.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => ReminderMail)
export class ReminderMailResolverBase {
  constructor(
    protected readonly service: ReminderMailService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "ReminderMail",
    action: "read",
    possession: "any",
  })
  async _reminderMailsMeta(
    @graphql.Args() args: ReminderMailCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [ReminderMail])
  @nestAccessControl.UseRoles({
    resource: "ReminderMail",
    action: "read",
    possession: "any",
  })
  async reminderMails(
    @graphql.Args() args: ReminderMailFindManyArgs
  ): Promise<ReminderMail[]> {
    return this.service.reminderMails(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => ReminderMail, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ReminderMail",
    action: "read",
    possession: "own",
  })
  async reminderMail(
    @graphql.Args() args: ReminderMailFindUniqueArgs
  ): Promise<ReminderMail | null> {
    const result = await this.service.reminderMail(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => ReminderMail)
  @nestAccessControl.UseRoles({
    resource: "ReminderMail",
    action: "create",
    possession: "any",
  })
  async createReminderMail(
    @graphql.Args() args: CreateReminderMailArgs
  ): Promise<ReminderMail> {
    return await this.service.createReminderMail({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => ReminderMail)
  @nestAccessControl.UseRoles({
    resource: "ReminderMail",
    action: "update",
    possession: "any",
  })
  async updateReminderMail(
    @graphql.Args() args: UpdateReminderMailArgs
  ): Promise<ReminderMail | null> {
    try {
      return await this.service.updateReminderMail({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => ReminderMail)
  @nestAccessControl.UseRoles({
    resource: "ReminderMail",
    action: "delete",
    possession: "any",
  })
  async deleteReminderMail(
    @graphql.Args() args: DeleteReminderMailArgs
  ): Promise<ReminderMail | null> {
    try {
      return await this.service.deleteReminderMail(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
