/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { OrigUser } from "./OrigUser";
import { OrigUserCountArgs } from "./OrigUserCountArgs";
import { OrigUserFindManyArgs } from "./OrigUserFindManyArgs";
import { OrigUserFindUniqueArgs } from "./OrigUserFindUniqueArgs";
import { CreateOrigUserArgs } from "./CreateOrigUserArgs";
import { UpdateOrigUserArgs } from "./UpdateOrigUserArgs";
import { DeleteOrigUserArgs } from "./DeleteOrigUserArgs";
import { AccountFindManyArgs } from "../../account/base/AccountFindManyArgs";
import { Account } from "../../account/base/Account";
import { ApiKeyFindManyArgs } from "../../apiKey/base/ApiKeyFindManyArgs";
import { ApiKey } from "../../apiKey/base/ApiKey";
import { AvailabilityFindManyArgs } from "../../availability/base/AvailabilityFindManyArgs";
import { Availability } from "../../availability/base/Availability";
import { BookingFindManyArgs } from "../../booking/base/BookingFindManyArgs";
import { Booking } from "../../booking/base/Booking";
import { CredentialFindManyArgs } from "../../credential/base/CredentialFindManyArgs";
import { Credential } from "../../credential/base/Credential";
import { EventTypeFindManyArgs } from "../../eventType/base/EventTypeFindManyArgs";
import { EventType } from "../../eventType/base/EventType";
import { FeedbackFindManyArgs } from "../../feedback/base/FeedbackFindManyArgs";
import { Feedback } from "../../feedback/base/Feedback";
import { ImpersonationFindManyArgs } from "../../impersonation/base/ImpersonationFindManyArgs";
import { Impersonation } from "../../impersonation/base/Impersonation";
import { ScheduleFindManyArgs } from "../../schedule/base/ScheduleFindManyArgs";
import { Schedule } from "../../schedule/base/Schedule";
import { SelectedCalendarFindManyArgs } from "../../selectedCalendar/base/SelectedCalendarFindManyArgs";
import { SelectedCalendar } from "../../selectedCalendar/base/SelectedCalendar";
import { SessionFindManyArgs } from "../../session/base/SessionFindManyArgs";
import { Session } from "../../session/base/Session";
import { MembershipFindManyArgs } from "../../membership/base/MembershipFindManyArgs";
import { Membership } from "../../membership/base/Membership";
import { WebhookFindManyArgs } from "../../webhook/base/WebhookFindManyArgs";
import { Webhook } from "../../webhook/base/Webhook";
import { WorkflowFindManyArgs } from "../../workflow/base/WorkflowFindManyArgs";
import { Workflow } from "../../workflow/base/Workflow";
import { DestinationCalendar } from "../../destinationCalendar/base/DestinationCalendar";
import { OrigUserService } from "../origUser.service";
@graphql.Resolver(() => OrigUser)
export class OrigUserResolverBase {
  constructor(protected readonly service: OrigUserService) {}

  async _origUsersMeta(
    @graphql.Args() args: OrigUserCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [OrigUser])
  async origUsers(
    @graphql.Args() args: OrigUserFindManyArgs
  ): Promise<OrigUser[]> {
    return this.service.origUsers(args);
  }

  @graphql.Query(() => OrigUser, { nullable: true })
  async origUser(
    @graphql.Args() args: OrigUserFindUniqueArgs
  ): Promise<OrigUser | null> {
    const result = await this.service.origUser(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => OrigUser)
  async createOrigUser(
    @graphql.Args() args: CreateOrigUserArgs
  ): Promise<OrigUser> {
    return await this.service.createOrigUser({
      ...args,
      data: {
        ...args.data,

        destinationCalendar: args.data.destinationCalendar
          ? {
              connect: args.data.destinationCalendar,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => OrigUser)
  async updateOrigUser(
    @graphql.Args() args: UpdateOrigUserArgs
  ): Promise<OrigUser | null> {
    try {
      return await this.service.updateOrigUser({
        ...args,
        data: {
          ...args.data,

          destinationCalendar: args.data.destinationCalendar
            ? {
                connect: args.data.destinationCalendar,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => OrigUser)
  async deleteOrigUser(
    @graphql.Args() args: DeleteOrigUserArgs
  ): Promise<OrigUser | null> {
    try {
      return await this.service.deleteOrigUser(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Account], { name: "accounts" })
  async findAccounts(
    @graphql.Parent() parent: OrigUser,
    @graphql.Args() args: AccountFindManyArgs
  ): Promise<Account[]> {
    const results = await this.service.findAccounts(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [ApiKey], { name: "apiKeys" })
  async findApiKeys(
    @graphql.Parent() parent: OrigUser,
    @graphql.Args() args: ApiKeyFindManyArgs
  ): Promise<ApiKey[]> {
    const results = await this.service.findApiKeys(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Availability], { name: "availability" })
  async findAvailability(
    @graphql.Parent() parent: OrigUser,
    @graphql.Args() args: AvailabilityFindManyArgs
  ): Promise<Availability[]> {
    const results = await this.service.findAvailability(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Booking], { name: "bookings" })
  async findBookings(
    @graphql.Parent() parent: OrigUser,
    @graphql.Args() args: BookingFindManyArgs
  ): Promise<Booking[]> {
    const results = await this.service.findBookings(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Credential], { name: "credentials" })
  async findCredentials(
    @graphql.Parent() parent: OrigUser,
    @graphql.Args() args: CredentialFindManyArgs
  ): Promise<Credential[]> {
    const results = await this.service.findCredentials(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [EventType], { name: "eventTypes" })
  async findEventTypes(
    @graphql.Parent() parent: OrigUser,
    @graphql.Args() args: EventTypeFindManyArgs
  ): Promise<EventType[]> {
    const results = await this.service.findEventTypes(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Feedback], { name: "feedback" })
  async findFeedback(
    @graphql.Parent() parent: OrigUser,
    @graphql.Args() args: FeedbackFindManyArgs
  ): Promise<Feedback[]> {
    const results = await this.service.findFeedback(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Impersonation], { name: "impersonatedBy" })
  async findImpersonatedBy(
    @graphql.Parent() parent: OrigUser,
    @graphql.Args() args: ImpersonationFindManyArgs
  ): Promise<Impersonation[]> {
    const results = await this.service.findImpersonatedBy(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Impersonation], { name: "impersonatedUsers" })
  async findImpersonatedUsers(
    @graphql.Parent() parent: OrigUser,
    @graphql.Args() args: ImpersonationFindManyArgs
  ): Promise<Impersonation[]> {
    const results = await this.service.findImpersonatedUsers(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Schedule], { name: "schedules" })
  async findSchedules(
    @graphql.Parent() parent: OrigUser,
    @graphql.Args() args: ScheduleFindManyArgs
  ): Promise<Schedule[]> {
    const results = await this.service.findSchedules(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [SelectedCalendar], { name: "selectedCalendars" })
  async findSelectedCalendars(
    @graphql.Parent() parent: OrigUser,
    @graphql.Args() args: SelectedCalendarFindManyArgs
  ): Promise<SelectedCalendar[]> {
    const results = await this.service.findSelectedCalendars(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Session], { name: "sessions" })
  async findSessions(
    @graphql.Parent() parent: OrigUser,
    @graphql.Args() args: SessionFindManyArgs
  ): Promise<Session[]> {
    const results = await this.service.findSessions(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Membership], { name: "teams" })
  async findTeams(
    @graphql.Parent() parent: OrigUser,
    @graphql.Args() args: MembershipFindManyArgs
  ): Promise<Membership[]> {
    const results = await this.service.findTeams(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Webhook], { name: "webhooks" })
  async findWebhooks(
    @graphql.Parent() parent: OrigUser,
    @graphql.Args() args: WebhookFindManyArgs
  ): Promise<Webhook[]> {
    const results = await this.service.findWebhooks(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Workflow], { name: "workflows" })
  async findWorkflows(
    @graphql.Parent() parent: OrigUser,
    @graphql.Args() args: WorkflowFindManyArgs
  ): Promise<Workflow[]> {
    const results = await this.service.findWorkflows(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => DestinationCalendar, {
    nullable: true,
    name: "destinationCalendar",
  })
  async getDestinationCalendar(
    @graphql.Parent() parent: OrigUser
  ): Promise<DestinationCalendar | null> {
    const result = await this.service.getDestinationCalendar(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
