import { AccountCreateNestedManyWithoutOrigUsersInput } from "./AccountCreateNestedManyWithoutOrigUsersInput";
import { ApiKeyCreateNestedManyWithoutOrigUsersInput } from "./ApiKeyCreateNestedManyWithoutOrigUsersInput";
import { AvailabilityCreateNestedManyWithoutOrigUsersInput } from "./AvailabilityCreateNestedManyWithoutOrigUsersInput";
import { BookingCreateNestedManyWithoutOrigUsersInput } from "./BookingCreateNestedManyWithoutOrigUsersInput";
import { CredentialCreateNestedManyWithoutOrigUsersInput } from "./CredentialCreateNestedManyWithoutOrigUsersInput";
import { DestinationCalendarWhereUniqueInput } from "../destinationCalendar/DestinationCalendarWhereUniqueInput";
import { EventTypeCreateNestedManyWithoutOrigUsersInput } from "./EventTypeCreateNestedManyWithoutOrigUsersInput";
import { FeedbackCreateNestedManyWithoutOrigUsersInput } from "./FeedbackCreateNestedManyWithoutOrigUsersInput";
import { ImpersonationCreateNestedManyWithoutOrigUsersInput } from "./ImpersonationCreateNestedManyWithoutOrigUsersInput";
import { InputJsonValue } from "../../types";
import { ScheduleCreateNestedManyWithoutOrigUsersInput } from "./ScheduleCreateNestedManyWithoutOrigUsersInput";
import { SelectedCalendarCreateNestedManyWithoutOrigUsersInput } from "./SelectedCalendarCreateNestedManyWithoutOrigUsersInput";
import { SessionCreateNestedManyWithoutOrigUsersInput } from "./SessionCreateNestedManyWithoutOrigUsersInput";
import { MembershipCreateNestedManyWithoutOrigUsersInput } from "./MembershipCreateNestedManyWithoutOrigUsersInput";
import { WebhookCreateNestedManyWithoutOrigUsersInput } from "./WebhookCreateNestedManyWithoutOrigUsersInput";
import { WorkflowCreateNestedManyWithoutOrigUsersInput } from "./WorkflowCreateNestedManyWithoutOrigUsersInput";

export type OrigUserCreateInput = {
  accounts?: AccountCreateNestedManyWithoutOrigUsersInput;
  allowDynamicBooking?: boolean | null;
  apiKeys?: ApiKeyCreateNestedManyWithoutOrigUsersInput;
  availability?: AvailabilityCreateNestedManyWithoutOrigUsersInput;
  avatar?: string | null;
  away: boolean;
  bio?: string | null;
  bookings?: BookingCreateNestedManyWithoutOrigUsersInput;
  brandColor: string;
  bufferTime: number;
  completedOnboarding: boolean;
  credentials?: CredentialCreateNestedManyWithoutOrigUsersInput;
  darkBrandColor: string;
  defaultScheduleId?: number | null;
  destinationCalendar?: DestinationCalendarWhereUniqueInput | null;
  disableImpersonation: boolean;
  email: string;
  emailVerified?: Date | null;
  endTime: number;
  eventTypes?: EventTypeCreateNestedManyWithoutOrigUsersInput;
  feedback?: FeedbackCreateNestedManyWithoutOrigUsersInput;
  hideBranding: boolean;
  identityProvider: "CAL" | "GOOGLE" | "SAML";
  identityProviderId?: string | null;
  impersonatedBy?: ImpersonationCreateNestedManyWithoutOrigUsersInput;
  impersonatedUsers?: ImpersonationCreateNestedManyWithoutOrigUsersInput;
  invitedTo?: number | null;
  locale?: string | null;
  metadata?: InputJsonValue;
  name?: string | null;
  password?: string | null;
  plan: "FREE" | "TRIAL" | "PRO";
  role: "USER" | "ADMIN";
  schedules?: ScheduleCreateNestedManyWithoutOrigUsersInput;
  selectedCalendars?: SelectedCalendarCreateNestedManyWithoutOrigUsersInput;
  sessions?: SessionCreateNestedManyWithoutOrigUsersInput;
  startTime: number;
  teams?: MembershipCreateNestedManyWithoutOrigUsersInput;
  theme?: string | null;
  timeFormat?: number | null;
  timeZone: string;
  trialEndsAt?: Date | null;
  twoFactorEnabled: boolean;
  twoFactorSecret?: string | null;
  username?: string | null;
  verified?: boolean | null;
  webhooks?: WebhookCreateNestedManyWithoutOrigUsersInput;
  weekStart: string;
  workflows?: WorkflowCreateNestedManyWithoutOrigUsersInput;
};
