import { AccountUpdateManyWithoutOrigUsersInput } from "./AccountUpdateManyWithoutOrigUsersInput";
import { ApiKeyUpdateManyWithoutOrigUsersInput } from "./ApiKeyUpdateManyWithoutOrigUsersInput";
import { AvailabilityUpdateManyWithoutOrigUsersInput } from "./AvailabilityUpdateManyWithoutOrigUsersInput";
import { BookingUpdateManyWithoutOrigUsersInput } from "./BookingUpdateManyWithoutOrigUsersInput";
import { CredentialUpdateManyWithoutOrigUsersInput } from "./CredentialUpdateManyWithoutOrigUsersInput";
import { DestinationCalendarWhereUniqueInput } from "../destinationCalendar/DestinationCalendarWhereUniqueInput";
import { EventTypeUpdateManyWithoutOrigUsersInput } from "./EventTypeUpdateManyWithoutOrigUsersInput";
import { FeedbackUpdateManyWithoutOrigUsersInput } from "./FeedbackUpdateManyWithoutOrigUsersInput";
import { ImpersonationUpdateManyWithoutOrigUsersInput } from "./ImpersonationUpdateManyWithoutOrigUsersInput";
import { InputJsonValue } from "../../types";
import { ScheduleUpdateManyWithoutOrigUsersInput } from "./ScheduleUpdateManyWithoutOrigUsersInput";
import { SelectedCalendarUpdateManyWithoutOrigUsersInput } from "./SelectedCalendarUpdateManyWithoutOrigUsersInput";
import { SessionUpdateManyWithoutOrigUsersInput } from "./SessionUpdateManyWithoutOrigUsersInput";
import { MembershipUpdateManyWithoutOrigUsersInput } from "./MembershipUpdateManyWithoutOrigUsersInput";
import { WebhookUpdateManyWithoutOrigUsersInput } from "./WebhookUpdateManyWithoutOrigUsersInput";
import { WorkflowUpdateManyWithoutOrigUsersInput } from "./WorkflowUpdateManyWithoutOrigUsersInput";

export type OrigUserUpdateInput = {
  accounts?: AccountUpdateManyWithoutOrigUsersInput;
  allowDynamicBooking?: boolean | null;
  apiKeys?: ApiKeyUpdateManyWithoutOrigUsersInput;
  availability?: AvailabilityUpdateManyWithoutOrigUsersInput;
  avatar?: string | null;
  away?: boolean;
  bio?: string | null;
  bookings?: BookingUpdateManyWithoutOrigUsersInput;
  brandColor?: string;
  bufferTime?: number;
  completedOnboarding?: boolean;
  credentials?: CredentialUpdateManyWithoutOrigUsersInput;
  darkBrandColor?: string;
  defaultScheduleId?: number | null;
  destinationCalendar?: DestinationCalendarWhereUniqueInput | null;
  disableImpersonation?: boolean;
  email?: string;
  emailVerified?: Date | null;
  endTime?: number;
  eventTypes?: EventTypeUpdateManyWithoutOrigUsersInput;
  feedback?: FeedbackUpdateManyWithoutOrigUsersInput;
  hideBranding?: boolean;
  identityProvider?: "CAL" | "GOOGLE" | "SAML";
  identityProviderId?: string | null;
  impersonatedBy?: ImpersonationUpdateManyWithoutOrigUsersInput;
  impersonatedUsers?: ImpersonationUpdateManyWithoutOrigUsersInput;
  invitedTo?: number | null;
  locale?: string | null;
  metadata?: InputJsonValue;
  name?: string | null;
  password?: string | null;
  plan?: "FREE" | "TRIAL" | "PRO";
  role?: "USER" | "ADMIN";
  schedules?: ScheduleUpdateManyWithoutOrigUsersInput;
  selectedCalendars?: SelectedCalendarUpdateManyWithoutOrigUsersInput;
  sessions?: SessionUpdateManyWithoutOrigUsersInput;
  startTime?: number;
  teams?: MembershipUpdateManyWithoutOrigUsersInput;
  theme?: string | null;
  timeFormat?: number | null;
  timeZone?: string;
  trialEndsAt?: Date | null;
  twoFactorEnabled?: boolean;
  twoFactorSecret?: string | null;
  username?: string | null;
  verified?: boolean | null;
  webhooks?: WebhookUpdateManyWithoutOrigUsersInput;
  weekStart?: string;
  workflows?: WorkflowUpdateManyWithoutOrigUsersInput;
};
