/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { DestinationCalendarService } from "../destinationCalendar.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DestinationCalendarCreateInput } from "./DestinationCalendarCreateInput";
import { DestinationCalendar } from "./DestinationCalendar";
import { DestinationCalendarFindManyArgs } from "./DestinationCalendarFindManyArgs";
import { DestinationCalendarWhereUniqueInput } from "./DestinationCalendarWhereUniqueInput";
import { DestinationCalendarUpdateInput } from "./DestinationCalendarUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class DestinationCalendarControllerBase {
  constructor(
    protected readonly service: DestinationCalendarService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: DestinationCalendar })
  @nestAccessControl.UseRoles({
    resource: "DestinationCalendar",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createDestinationCalendar(
    @common.Body() data: DestinationCalendarCreateInput
  ): Promise<DestinationCalendar> {
    return await this.service.createDestinationCalendar({
      data: {
        ...data,

        booking: data.booking
          ? {
              connect: data.booking,
            }
          : undefined,

        credential: data.credential
          ? {
              connect: data.credential,
            }
          : undefined,

        eventType: data.eventType
          ? {
              connect: data.eventType,
            }
          : undefined,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        booking: {
          select: {
            id: true,
          },
        },

        credential: {
          select: {
            id: true,
          },
        },

        eventType: {
          select: {
            id: true,
          },
        },

        externalId: true,
        id: true,
        integration: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [DestinationCalendar] })
  @ApiNestedQuery(DestinationCalendarFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "DestinationCalendar",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async destinationCalendars(
    @common.Req() request: Request
  ): Promise<DestinationCalendar[]> {
    const args = plainToClass(DestinationCalendarFindManyArgs, request.query);
    return this.service.destinationCalendars({
      ...args,
      select: {
        booking: {
          select: {
            id: true,
          },
        },

        credential: {
          select: {
            id: true,
          },
        },

        eventType: {
          select: {
            id: true,
          },
        },

        externalId: true,
        id: true,
        integration: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: DestinationCalendar })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DestinationCalendar",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async destinationCalendar(
    @common.Param() params: DestinationCalendarWhereUniqueInput
  ): Promise<DestinationCalendar | null> {
    const result = await this.service.destinationCalendar({
      where: params,
      select: {
        booking: {
          select: {
            id: true,
          },
        },

        credential: {
          select: {
            id: true,
          },
        },

        eventType: {
          select: {
            id: true,
          },
        },

        externalId: true,
        id: true,
        integration: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: DestinationCalendar })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DestinationCalendar",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateDestinationCalendar(
    @common.Param() params: DestinationCalendarWhereUniqueInput,
    @common.Body() data: DestinationCalendarUpdateInput
  ): Promise<DestinationCalendar | null> {
    try {
      return await this.service.updateDestinationCalendar({
        where: params,
        data: {
          ...data,

          booking: data.booking
            ? {
                connect: data.booking,
              }
            : undefined,

          credential: data.credential
            ? {
                connect: data.credential,
              }
            : undefined,

          eventType: data.eventType
            ? {
                connect: data.eventType,
              }
            : undefined,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          booking: {
            select: {
              id: true,
            },
          },

          credential: {
            select: {
              id: true,
            },
          },

          eventType: {
            select: {
              id: true,
            },
          },

          externalId: true,
          id: true,
          integration: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: DestinationCalendar })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DestinationCalendar",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteDestinationCalendar(
    @common.Param() params: DestinationCalendarWhereUniqueInput
  ): Promise<DestinationCalendar | null> {
    try {
      return await this.service.deleteDestinationCalendar({
        where: params,
        select: {
          booking: {
            select: {
              id: true,
            },
          },

          credential: {
            select: {
              id: true,
            },
          },

          eventType: {
            select: {
              id: true,
            },
          },

          externalId: true,
          id: true,
          integration: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
