/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { EventType } from "./EventType";
import { EventTypeCountArgs } from "./EventTypeCountArgs";
import { EventTypeFindManyArgs } from "./EventTypeFindManyArgs";
import { EventTypeFindUniqueArgs } from "./EventTypeFindUniqueArgs";
import { CreateEventTypeArgs } from "./CreateEventTypeArgs";
import { UpdateEventTypeArgs } from "./UpdateEventTypeArgs";
import { DeleteEventTypeArgs } from "./DeleteEventTypeArgs";
import { AvailabilityFindManyArgs } from "../../availability/base/AvailabilityFindManyArgs";
import { Availability } from "../../availability/base/Availability";
import { BookingFindManyArgs } from "../../booking/base/BookingFindManyArgs";
import { Booking } from "../../booking/base/Booking";
import { EventTypeCustomInputFindManyArgs } from "../../eventTypeCustomInput/base/EventTypeCustomInputFindManyArgs";
import { EventTypeCustomInput } from "../../eventTypeCustomInput/base/EventTypeCustomInput";
import { OrigUserFindManyArgs } from "../../origUser/base/OrigUserFindManyArgs";
import { OrigUser } from "../../origUser/base/OrigUser";
import { WebhookFindManyArgs } from "../../webhook/base/WebhookFindManyArgs";
import { Webhook } from "../../webhook/base/Webhook";
import { WorkflowsOnEventTypeFindManyArgs } from "../../workflowsOnEventType/base/WorkflowsOnEventTypeFindManyArgs";
import { WorkflowsOnEventType } from "../../workflowsOnEventType/base/WorkflowsOnEventType";
import { DestinationCalendar } from "../../destinationCalendar/base/DestinationCalendar";
import { HashedLink } from "../../hashedLink/base/HashedLink";
import { Schedule } from "../../schedule/base/Schedule";
import { Team } from "../../team/base/Team";
import { EventTypeService } from "../eventType.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => EventType)
export class EventTypeResolverBase {
  constructor(
    protected readonly service: EventTypeService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "EventType",
    action: "read",
    possession: "any",
  })
  async _eventTypesMeta(
    @graphql.Args() args: EventTypeCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [EventType])
  @nestAccessControl.UseRoles({
    resource: "EventType",
    action: "read",
    possession: "any",
  })
  async eventTypes(
    @graphql.Args() args: EventTypeFindManyArgs
  ): Promise<EventType[]> {
    return this.service.eventTypes(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => EventType, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "EventType",
    action: "read",
    possession: "own",
  })
  async eventType(
    @graphql.Args() args: EventTypeFindUniqueArgs
  ): Promise<EventType | null> {
    const result = await this.service.eventType(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => EventType)
  @nestAccessControl.UseRoles({
    resource: "EventType",
    action: "create",
    possession: "any",
  })
  async createEventType(
    @graphql.Args() args: CreateEventTypeArgs
  ): Promise<EventType> {
    return await this.service.createEventType({
      ...args,
      data: {
        ...args.data,

        destinationCalendar: args.data.destinationCalendar
          ? {
              connect: args.data.destinationCalendar,
            }
          : undefined,

        hashedLink: args.data.hashedLink
          ? {
              connect: args.data.hashedLink,
            }
          : undefined,

        schedule: args.data.schedule
          ? {
              connect: args.data.schedule,
            }
          : undefined,

        team: args.data.team
          ? {
              connect: args.data.team,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => EventType)
  @nestAccessControl.UseRoles({
    resource: "EventType",
    action: "update",
    possession: "any",
  })
  async updateEventType(
    @graphql.Args() args: UpdateEventTypeArgs
  ): Promise<EventType | null> {
    try {
      return await this.service.updateEventType({
        ...args,
        data: {
          ...args.data,

          destinationCalendar: args.data.destinationCalendar
            ? {
                connect: args.data.destinationCalendar,
              }
            : undefined,

          hashedLink: args.data.hashedLink
            ? {
                connect: args.data.hashedLink,
              }
            : undefined,

          schedule: args.data.schedule
            ? {
                connect: args.data.schedule,
              }
            : undefined,

          team: args.data.team
            ? {
                connect: args.data.team,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => EventType)
  @nestAccessControl.UseRoles({
    resource: "EventType",
    action: "delete",
    possession: "any",
  })
  async deleteEventType(
    @graphql.Args() args: DeleteEventTypeArgs
  ): Promise<EventType | null> {
    try {
      return await this.service.deleteEventType(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Availability], { name: "availability" })
  @nestAccessControl.UseRoles({
    resource: "Availability",
    action: "read",
    possession: "any",
  })
  async findAvailability(
    @graphql.Parent() parent: EventType,
    @graphql.Args() args: AvailabilityFindManyArgs
  ): Promise<Availability[]> {
    const results = await this.service.findAvailability(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Booking], { name: "bookings" })
  @nestAccessControl.UseRoles({
    resource: "Booking",
    action: "read",
    possession: "any",
  })
  async findBookings(
    @graphql.Parent() parent: EventType,
    @graphql.Args() args: BookingFindManyArgs
  ): Promise<Booking[]> {
    const results = await this.service.findBookings(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [EventTypeCustomInput], { name: "customInputs" })
  @nestAccessControl.UseRoles({
    resource: "EventTypeCustomInput",
    action: "read",
    possession: "any",
  })
  async findCustomInputs(
    @graphql.Parent() parent: EventType,
    @graphql.Args() args: EventTypeCustomInputFindManyArgs
  ): Promise<EventTypeCustomInput[]> {
    const results = await this.service.findCustomInputs(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [OrigUser], { name: "users" })
  @nestAccessControl.UseRoles({
    resource: "OrigUser",
    action: "read",
    possession: "any",
  })
  async findUsers(
    @graphql.Parent() parent: EventType,
    @graphql.Args() args: OrigUserFindManyArgs
  ): Promise<OrigUser[]> {
    const results = await this.service.findUsers(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Webhook], { name: "webhooks" })
  @nestAccessControl.UseRoles({
    resource: "Webhook",
    action: "read",
    possession: "any",
  })
  async findWebhooks(
    @graphql.Parent() parent: EventType,
    @graphql.Args() args: WebhookFindManyArgs
  ): Promise<Webhook[]> {
    const results = await this.service.findWebhooks(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [WorkflowsOnEventType], { name: "workflows" })
  @nestAccessControl.UseRoles({
    resource: "WorkflowsOnEventType",
    action: "read",
    possession: "any",
  })
  async findWorkflows(
    @graphql.Parent() parent: EventType,
    @graphql.Args() args: WorkflowsOnEventTypeFindManyArgs
  ): Promise<WorkflowsOnEventType[]> {
    const results = await this.service.findWorkflows(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => DestinationCalendar, {
    nullable: true,
    name: "destinationCalendar",
  })
  @nestAccessControl.UseRoles({
    resource: "DestinationCalendar",
    action: "read",
    possession: "any",
  })
  async getDestinationCalendar(
    @graphql.Parent() parent: EventType
  ): Promise<DestinationCalendar | null> {
    const result = await this.service.getDestinationCalendar(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => HashedLink, {
    nullable: true,
    name: "hashedLink",
  })
  @nestAccessControl.UseRoles({
    resource: "HashedLink",
    action: "read",
    possession: "any",
  })
  async getHashedLink(
    @graphql.Parent() parent: EventType
  ): Promise<HashedLink | null> {
    const result = await this.service.getHashedLink(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Schedule, {
    nullable: true,
    name: "schedule",
  })
  @nestAccessControl.UseRoles({
    resource: "Schedule",
    action: "read",
    possession: "any",
  })
  async getSchedule(
    @graphql.Parent() parent: EventType
  ): Promise<Schedule | null> {
    const result = await this.service.getSchedule(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Team, {
    nullable: true,
    name: "team",
  })
  @nestAccessControl.UseRoles({
    resource: "Team",
    action: "read",
    possession: "any",
  })
  async getTeam(@graphql.Parent() parent: EventType): Promise<Team | null> {
    const result = await this.service.getTeam(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
