/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { WorkflowReminderService } from "../workflowReminder.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { WorkflowReminderCreateInput } from "./WorkflowReminderCreateInput";
import { WorkflowReminder } from "./WorkflowReminder";
import { WorkflowReminderFindManyArgs } from "./WorkflowReminderFindManyArgs";
import { WorkflowReminderWhereUniqueInput } from "./WorkflowReminderWhereUniqueInput";
import { WorkflowReminderUpdateInput } from "./WorkflowReminderUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class WorkflowReminderControllerBase {
  constructor(
    protected readonly service: WorkflowReminderService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: WorkflowReminder })
  @nestAccessControl.UseRoles({
    resource: "WorkflowReminder",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createWorkflowReminder(
    @common.Body() data: WorkflowReminderCreateInput
  ): Promise<WorkflowReminder> {
    return await this.service.createWorkflowReminder({
      data: {
        ...data,

        booking: data.booking
          ? {
              connect: data.booking,
            }
          : undefined,

        workflowStep: {
          connect: data.workflowStep,
        },
      },
      select: {
        booking: {
          select: {
            id: true,
          },
        },

        id: true,
        method: true,
        referenceId: true,
        scheduled: true,
        scheduledDate: true,

        workflowStep: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [WorkflowReminder] })
  @ApiNestedQuery(WorkflowReminderFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "WorkflowReminder",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async workflowReminders(
    @common.Req() request: Request
  ): Promise<WorkflowReminder[]> {
    const args = plainToClass(WorkflowReminderFindManyArgs, request.query);
    return this.service.workflowReminders({
      ...args,
      select: {
        booking: {
          select: {
            id: true,
          },
        },

        id: true,
        method: true,
        referenceId: true,
        scheduled: true,
        scheduledDate: true,

        workflowStep: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: WorkflowReminder })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "WorkflowReminder",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async workflowReminder(
    @common.Param() params: WorkflowReminderWhereUniqueInput
  ): Promise<WorkflowReminder | null> {
    const result = await this.service.workflowReminder({
      where: params,
      select: {
        booking: {
          select: {
            id: true,
          },
        },

        id: true,
        method: true,
        referenceId: true,
        scheduled: true,
        scheduledDate: true,

        workflowStep: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: WorkflowReminder })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "WorkflowReminder",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateWorkflowReminder(
    @common.Param() params: WorkflowReminderWhereUniqueInput,
    @common.Body() data: WorkflowReminderUpdateInput
  ): Promise<WorkflowReminder | null> {
    try {
      return await this.service.updateWorkflowReminder({
        where: params,
        data: {
          ...data,

          booking: data.booking
            ? {
                connect: data.booking,
              }
            : undefined,

          workflowStep: {
            connect: data.workflowStep,
          },
        },
        select: {
          booking: {
            select: {
              id: true,
            },
          },

          id: true,
          method: true,
          referenceId: true,
          scheduled: true,
          scheduledDate: true,

          workflowStep: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: WorkflowReminder })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "WorkflowReminder",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteWorkflowReminder(
    @common.Param() params: WorkflowReminderWhereUniqueInput
  ): Promise<WorkflowReminder | null> {
    try {
      return await this.service.deleteWorkflowReminder({
        where: params,
        select: {
          booking: {
            select: {
              id: true,
            },
          },

          id: true,
          method: true,
          referenceId: true,
          scheduled: true,
          scheduledDate: true,

          workflowStep: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
