/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Credential } from "./Credential";
import { CredentialCountArgs } from "./CredentialCountArgs";
import { CredentialFindManyArgs } from "./CredentialFindManyArgs";
import { CredentialFindUniqueArgs } from "./CredentialFindUniqueArgs";
import { CreateCredentialArgs } from "./CreateCredentialArgs";
import { UpdateCredentialArgs } from "./UpdateCredentialArgs";
import { DeleteCredentialArgs } from "./DeleteCredentialArgs";
import { DestinationCalendarFindManyArgs } from "../../destinationCalendar/base/DestinationCalendarFindManyArgs";
import { DestinationCalendar } from "../../destinationCalendar/base/DestinationCalendar";
import { AppModel } from "../../appModel/base/AppModel";
import { OrigUser } from "../../origUser/base/OrigUser";
import { CredentialService } from "../credential.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Credential)
export class CredentialResolverBase {
  constructor(
    protected readonly service: CredentialService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Credential",
    action: "read",
    possession: "any",
  })
  async _credentialsMeta(
    @graphql.Args() args: CredentialCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Credential])
  @nestAccessControl.UseRoles({
    resource: "Credential",
    action: "read",
    possession: "any",
  })
  async credentials(
    @graphql.Args() args: CredentialFindManyArgs
  ): Promise<Credential[]> {
    return this.service.credentials(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Credential, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Credential",
    action: "read",
    possession: "own",
  })
  async credential(
    @graphql.Args() args: CredentialFindUniqueArgs
  ): Promise<Credential | null> {
    const result = await this.service.credential(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Credential)
  @nestAccessControl.UseRoles({
    resource: "Credential",
    action: "create",
    possession: "any",
  })
  async createCredential(
    @graphql.Args() args: CreateCredentialArgs
  ): Promise<Credential> {
    return await this.service.createCredential({
      ...args,
      data: {
        ...args.data,

        appField: args.data.appField
          ? {
              connect: args.data.appField,
            }
          : undefined,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Credential)
  @nestAccessControl.UseRoles({
    resource: "Credential",
    action: "update",
    possession: "any",
  })
  async updateCredential(
    @graphql.Args() args: UpdateCredentialArgs
  ): Promise<Credential | null> {
    try {
      return await this.service.updateCredential({
        ...args,
        data: {
          ...args.data,

          appField: args.data.appField
            ? {
                connect: args.data.appField,
              }
            : undefined,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Credential)
  @nestAccessControl.UseRoles({
    resource: "Credential",
    action: "delete",
    possession: "any",
  })
  async deleteCredential(
    @graphql.Args() args: DeleteCredentialArgs
  ): Promise<Credential | null> {
    try {
      return await this.service.deleteCredential(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [DestinationCalendar], {
    name: "destinationCalendars",
  })
  @nestAccessControl.UseRoles({
    resource: "DestinationCalendar",
    action: "read",
    possession: "any",
  })
  async findDestinationCalendars(
    @graphql.Parent() parent: Credential,
    @graphql.Args() args: DestinationCalendarFindManyArgs
  ): Promise<DestinationCalendar[]> {
    const results = await this.service.findDestinationCalendars(
      parent.id,
      args
    );

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => AppModel, {
    nullable: true,
    name: "appField",
  })
  @nestAccessControl.UseRoles({
    resource: "AppModel",
    action: "read",
    possession: "any",
  })
  async getAppField(
    @graphql.Parent() parent: Credential
  ): Promise<AppModel | null> {
    const result = await this.service.getAppField(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => OrigUser, {
    nullable: true,
    name: "user",
  })
  @nestAccessControl.UseRoles({
    resource: "OrigUser",
    action: "read",
    possession: "any",
  })
  async getUser(
    @graphql.Parent() parent: Credential
  ): Promise<OrigUser | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
