/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ImpersonationService } from "../impersonation.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ImpersonationCreateInput } from "./ImpersonationCreateInput";
import { Impersonation } from "./Impersonation";
import { ImpersonationFindManyArgs } from "./ImpersonationFindManyArgs";
import { ImpersonationWhereUniqueInput } from "./ImpersonationWhereUniqueInput";
import { ImpersonationUpdateInput } from "./ImpersonationUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ImpersonationControllerBase {
  constructor(
    protected readonly service: ImpersonationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Impersonation })
  @nestAccessControl.UseRoles({
    resource: "Impersonation",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createImpersonation(
    @common.Body() data: ImpersonationCreateInput
  ): Promise<Impersonation> {
    return await this.service.createImpersonation({
      data: {
        ...data,

        impersonatedBy: {
          connect: data.impersonatedBy,
        },

        impersonatedUser: {
          connect: data.impersonatedUser,
        },
      },
      select: {
        createdAt: true,
        id: true,

        impersonatedBy: {
          select: {
            id: true,
          },
        },

        impersonatedUser: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Impersonation] })
  @ApiNestedQuery(ImpersonationFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Impersonation",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async impersonations(
    @common.Req() request: Request
  ): Promise<Impersonation[]> {
    const args = plainToClass(ImpersonationFindManyArgs, request.query);
    return this.service.impersonations({
      ...args,
      select: {
        createdAt: true,
        id: true,

        impersonatedBy: {
          select: {
            id: true,
          },
        },

        impersonatedUser: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Impersonation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Impersonation",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async impersonation(
    @common.Param() params: ImpersonationWhereUniqueInput
  ): Promise<Impersonation | null> {
    const result = await this.service.impersonation({
      where: params,
      select: {
        createdAt: true,
        id: true,

        impersonatedBy: {
          select: {
            id: true,
          },
        },

        impersonatedUser: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Impersonation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Impersonation",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateImpersonation(
    @common.Param() params: ImpersonationWhereUniqueInput,
    @common.Body() data: ImpersonationUpdateInput
  ): Promise<Impersonation | null> {
    try {
      return await this.service.updateImpersonation({
        where: params,
        data: {
          ...data,

          impersonatedBy: {
            connect: data.impersonatedBy,
          },

          impersonatedUser: {
            connect: data.impersonatedUser,
          },
        },
        select: {
          createdAt: true,
          id: true,

          impersonatedBy: {
            select: {
              id: true,
            },
          },

          impersonatedUser: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Impersonation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Impersonation",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteImpersonation(
    @common.Param() params: ImpersonationWhereUniqueInput
  ): Promise<Impersonation | null> {
    try {
      return await this.service.deleteImpersonation({
        where: params,
        select: {
          createdAt: true,
          id: true,

          impersonatedBy: {
            select: {
              id: true,
            },
          },

          impersonatedUser: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
