/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { WorkflowsOnEventType } from "./WorkflowsOnEventType";
import { WorkflowsOnEventTypeCountArgs } from "./WorkflowsOnEventTypeCountArgs";
import { WorkflowsOnEventTypeFindManyArgs } from "./WorkflowsOnEventTypeFindManyArgs";
import { WorkflowsOnEventTypeFindUniqueArgs } from "./WorkflowsOnEventTypeFindUniqueArgs";
import { CreateWorkflowsOnEventTypeArgs } from "./CreateWorkflowsOnEventTypeArgs";
import { UpdateWorkflowsOnEventTypeArgs } from "./UpdateWorkflowsOnEventTypeArgs";
import { DeleteWorkflowsOnEventTypeArgs } from "./DeleteWorkflowsOnEventTypeArgs";
import { EventType } from "../../eventType/base/EventType";
import { Workflow } from "../../workflow/base/Workflow";
import { WorkflowsOnEventTypeService } from "../workflowsOnEventType.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => WorkflowsOnEventType)
export class WorkflowsOnEventTypeResolverBase {
  constructor(
    protected readonly service: WorkflowsOnEventTypeService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "WorkflowsOnEventType",
    action: "read",
    possession: "any",
  })
  async _workflowsOnEventTypesMeta(
    @graphql.Args() args: WorkflowsOnEventTypeCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [WorkflowsOnEventType])
  @nestAccessControl.UseRoles({
    resource: "WorkflowsOnEventType",
    action: "read",
    possession: "any",
  })
  async workflowsOnEventTypes(
    @graphql.Args() args: WorkflowsOnEventTypeFindManyArgs
  ): Promise<WorkflowsOnEventType[]> {
    return this.service.workflowsOnEventTypes(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => WorkflowsOnEventType, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "WorkflowsOnEventType",
    action: "read",
    possession: "own",
  })
  async workflowsOnEventType(
    @graphql.Args() args: WorkflowsOnEventTypeFindUniqueArgs
  ): Promise<WorkflowsOnEventType | null> {
    const result = await this.service.workflowsOnEventType(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => WorkflowsOnEventType)
  @nestAccessControl.UseRoles({
    resource: "WorkflowsOnEventType",
    action: "create",
    possession: "any",
  })
  async createWorkflowsOnEventType(
    @graphql.Args() args: CreateWorkflowsOnEventTypeArgs
  ): Promise<WorkflowsOnEventType> {
    return await this.service.createWorkflowsOnEventType({
      ...args,
      data: {
        ...args.data,

        eventType: {
          connect: args.data.eventType,
        },

        workflow: {
          connect: args.data.workflow,
        },
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => WorkflowsOnEventType)
  @nestAccessControl.UseRoles({
    resource: "WorkflowsOnEventType",
    action: "update",
    possession: "any",
  })
  async updateWorkflowsOnEventType(
    @graphql.Args() args: UpdateWorkflowsOnEventTypeArgs
  ): Promise<WorkflowsOnEventType | null> {
    try {
      return await this.service.updateWorkflowsOnEventType({
        ...args,
        data: {
          ...args.data,

          eventType: {
            connect: args.data.eventType,
          },

          workflow: {
            connect: args.data.workflow,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => WorkflowsOnEventType)
  @nestAccessControl.UseRoles({
    resource: "WorkflowsOnEventType",
    action: "delete",
    possession: "any",
  })
  async deleteWorkflowsOnEventType(
    @graphql.Args() args: DeleteWorkflowsOnEventTypeArgs
  ): Promise<WorkflowsOnEventType | null> {
    try {
      return await this.service.deleteWorkflowsOnEventType(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => EventType, {
    nullable: true,
    name: "eventType",
  })
  @nestAccessControl.UseRoles({
    resource: "EventType",
    action: "read",
    possession: "any",
  })
  async getEventType(
    @graphql.Parent() parent: WorkflowsOnEventType
  ): Promise<EventType | null> {
    const result = await this.service.getEventType(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Workflow, {
    nullable: true,
    name: "workflow",
  })
  @nestAccessControl.UseRoles({
    resource: "Workflow",
    action: "read",
    possession: "any",
  })
  async getWorkflow(
    @graphql.Parent() parent: WorkflowsOnEventType
  ): Promise<Workflow | null> {
    const result = await this.service.getWorkflow(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
