/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { WorkflowsOnEventTypeService } from "../workflowsOnEventType.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { WorkflowsOnEventTypeCreateInput } from "./WorkflowsOnEventTypeCreateInput";
import { WorkflowsOnEventType } from "./WorkflowsOnEventType";
import { WorkflowsOnEventTypeFindManyArgs } from "./WorkflowsOnEventTypeFindManyArgs";
import { WorkflowsOnEventTypeWhereUniqueInput } from "./WorkflowsOnEventTypeWhereUniqueInput";
import { WorkflowsOnEventTypeUpdateInput } from "./WorkflowsOnEventTypeUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class WorkflowsOnEventTypeControllerBase {
  constructor(
    protected readonly service: WorkflowsOnEventTypeService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: WorkflowsOnEventType })
  @nestAccessControl.UseRoles({
    resource: "WorkflowsOnEventType",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createWorkflowsOnEventType(
    @common.Body() data: WorkflowsOnEventTypeCreateInput
  ): Promise<WorkflowsOnEventType> {
    return await this.service.createWorkflowsOnEventType({
      data: {
        ...data,

        eventType: {
          connect: data.eventType,
        },

        workflow: {
          connect: data.workflow,
        },
      },
      select: {
        eventType: {
          select: {
            id: true,
          },
        },

        id: true,

        workflow: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [WorkflowsOnEventType] })
  @ApiNestedQuery(WorkflowsOnEventTypeFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "WorkflowsOnEventType",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async workflowsOnEventTypes(
    @common.Req() request: Request
  ): Promise<WorkflowsOnEventType[]> {
    const args = plainToClass(WorkflowsOnEventTypeFindManyArgs, request.query);
    return this.service.workflowsOnEventTypes({
      ...args,
      select: {
        eventType: {
          select: {
            id: true,
          },
        },

        id: true,

        workflow: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: WorkflowsOnEventType })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "WorkflowsOnEventType",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async workflowsOnEventType(
    @common.Param() params: WorkflowsOnEventTypeWhereUniqueInput
  ): Promise<WorkflowsOnEventType | null> {
    const result = await this.service.workflowsOnEventType({
      where: params,
      select: {
        eventType: {
          select: {
            id: true,
          },
        },

        id: true,

        workflow: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: WorkflowsOnEventType })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "WorkflowsOnEventType",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateWorkflowsOnEventType(
    @common.Param() params: WorkflowsOnEventTypeWhereUniqueInput,
    @common.Body() data: WorkflowsOnEventTypeUpdateInput
  ): Promise<WorkflowsOnEventType | null> {
    try {
      return await this.service.updateWorkflowsOnEventType({
        where: params,
        data: {
          ...data,

          eventType: {
            connect: data.eventType,
          },

          workflow: {
            connect: data.workflow,
          },
        },
        select: {
          eventType: {
            select: {
              id: true,
            },
          },

          id: true,

          workflow: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: WorkflowsOnEventType })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "WorkflowsOnEventType",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteWorkflowsOnEventType(
    @common.Param() params: WorkflowsOnEventTypeWhereUniqueInput
  ): Promise<WorkflowsOnEventType | null> {
    try {
      return await this.service.deleteWorkflowsOnEventType({
        where: params,
        select: {
          eventType: {
            select: {
              id: true,
            },
          },

          id: true,

          workflow: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
