/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { HashedLinkService } from "../hashedLink.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { HashedLinkCreateInput } from "./HashedLinkCreateInput";
import { HashedLink } from "./HashedLink";
import { HashedLinkFindManyArgs } from "./HashedLinkFindManyArgs";
import { HashedLinkWhereUniqueInput } from "./HashedLinkWhereUniqueInput";
import { HashedLinkUpdateInput } from "./HashedLinkUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class HashedLinkControllerBase {
  constructor(
    protected readonly service: HashedLinkService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: HashedLink })
  @nestAccessControl.UseRoles({
    resource: "HashedLink",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createHashedLink(
    @common.Body() data: HashedLinkCreateInput
  ): Promise<HashedLink> {
    return await this.service.createHashedLink({
      data: {
        ...data,

        eventType: {
          connect: data.eventType,
        },
      },
      select: {
        eventType: {
          select: {
            id: true,
          },
        },

        id: true,
        link: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [HashedLink] })
  @ApiNestedQuery(HashedLinkFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "HashedLink",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async hashedLinks(@common.Req() request: Request): Promise<HashedLink[]> {
    const args = plainToClass(HashedLinkFindManyArgs, request.query);
    return this.service.hashedLinks({
      ...args,
      select: {
        eventType: {
          select: {
            id: true,
          },
        },

        id: true,
        link: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: HashedLink })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "HashedLink",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async hashedLink(
    @common.Param() params: HashedLinkWhereUniqueInput
  ): Promise<HashedLink | null> {
    const result = await this.service.hashedLink({
      where: params,
      select: {
        eventType: {
          select: {
            id: true,
          },
        },

        id: true,
        link: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: HashedLink })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "HashedLink",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateHashedLink(
    @common.Param() params: HashedLinkWhereUniqueInput,
    @common.Body() data: HashedLinkUpdateInput
  ): Promise<HashedLink | null> {
    try {
      return await this.service.updateHashedLink({
        where: params,
        data: {
          ...data,

          eventType: {
            connect: data.eventType,
          },
        },
        select: {
          eventType: {
            select: {
              id: true,
            },
          },

          id: true,
          link: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: HashedLink })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "HashedLink",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteHashedLink(
    @common.Param() params: HashedLinkWhereUniqueInput
  ): Promise<HashedLink | null> {
    try {
      return await this.service.deleteHashedLink({
        where: params,
        select: {
          eventType: {
            select: {
              id: true,
            },
          },

          id: true,
          link: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
