/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { BookingReference } from "./BookingReference";
import { BookingReferenceCountArgs } from "./BookingReferenceCountArgs";
import { BookingReferenceFindManyArgs } from "./BookingReferenceFindManyArgs";
import { BookingReferenceFindUniqueArgs } from "./BookingReferenceFindUniqueArgs";
import { CreateBookingReferenceArgs } from "./CreateBookingReferenceArgs";
import { UpdateBookingReferenceArgs } from "./UpdateBookingReferenceArgs";
import { DeleteBookingReferenceArgs } from "./DeleteBookingReferenceArgs";
import { Booking } from "../../booking/base/Booking";
import { BookingReferenceService } from "../bookingReference.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => BookingReference)
export class BookingReferenceResolverBase {
  constructor(
    protected readonly service: BookingReferenceService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "BookingReference",
    action: "read",
    possession: "any",
  })
  async _bookingReferencesMeta(
    @graphql.Args() args: BookingReferenceCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [BookingReference])
  @nestAccessControl.UseRoles({
    resource: "BookingReference",
    action: "read",
    possession: "any",
  })
  async bookingReferences(
    @graphql.Args() args: BookingReferenceFindManyArgs
  ): Promise<BookingReference[]> {
    return this.service.bookingReferences(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => BookingReference, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "BookingReference",
    action: "read",
    possession: "own",
  })
  async bookingReference(
    @graphql.Args() args: BookingReferenceFindUniqueArgs
  ): Promise<BookingReference | null> {
    const result = await this.service.bookingReference(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => BookingReference)
  @nestAccessControl.UseRoles({
    resource: "BookingReference",
    action: "create",
    possession: "any",
  })
  async createBookingReference(
    @graphql.Args() args: CreateBookingReferenceArgs
  ): Promise<BookingReference> {
    return await this.service.createBookingReference({
      ...args,
      data: {
        ...args.data,

        booking: args.data.booking
          ? {
              connect: args.data.booking,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => BookingReference)
  @nestAccessControl.UseRoles({
    resource: "BookingReference",
    action: "update",
    possession: "any",
  })
  async updateBookingReference(
    @graphql.Args() args: UpdateBookingReferenceArgs
  ): Promise<BookingReference | null> {
    try {
      return await this.service.updateBookingReference({
        ...args,
        data: {
          ...args.data,

          booking: args.data.booking
            ? {
                connect: args.data.booking,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => BookingReference)
  @nestAccessControl.UseRoles({
    resource: "BookingReference",
    action: "delete",
    possession: "any",
  })
  async deleteBookingReference(
    @graphql.Args() args: DeleteBookingReferenceArgs
  ): Promise<BookingReference | null> {
    try {
      return await this.service.deleteBookingReference(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Booking, {
    nullable: true,
    name: "booking",
  })
  @nestAccessControl.UseRoles({
    resource: "Booking",
    action: "read",
    possession: "any",
  })
  async getBooking(
    @graphql.Parent() parent: BookingReference
  ): Promise<Booking | null> {
    const result = await this.service.getBooking(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
