/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { SelectedCalendar } from "./SelectedCalendar";
import { SelectedCalendarCountArgs } from "./SelectedCalendarCountArgs";
import { SelectedCalendarFindManyArgs } from "./SelectedCalendarFindManyArgs";
import { SelectedCalendarFindUniqueArgs } from "./SelectedCalendarFindUniqueArgs";
import { CreateSelectedCalendarArgs } from "./CreateSelectedCalendarArgs";
import { UpdateSelectedCalendarArgs } from "./UpdateSelectedCalendarArgs";
import { DeleteSelectedCalendarArgs } from "./DeleteSelectedCalendarArgs";
import { OrigUser } from "../../origUser/base/OrigUser";
import { SelectedCalendarService } from "../selectedCalendar.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => SelectedCalendar)
export class SelectedCalendarResolverBase {
  constructor(
    protected readonly service: SelectedCalendarService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "SelectedCalendar",
    action: "read",
    possession: "any",
  })
  async _selectedCalendarsMeta(
    @graphql.Args() args: SelectedCalendarCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [SelectedCalendar])
  @nestAccessControl.UseRoles({
    resource: "SelectedCalendar",
    action: "read",
    possession: "any",
  })
  async selectedCalendars(
    @graphql.Args() args: SelectedCalendarFindManyArgs
  ): Promise<SelectedCalendar[]> {
    return this.service.selectedCalendars(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => SelectedCalendar, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "SelectedCalendar",
    action: "read",
    possession: "own",
  })
  async selectedCalendar(
    @graphql.Args() args: SelectedCalendarFindUniqueArgs
  ): Promise<SelectedCalendar | null> {
    const result = await this.service.selectedCalendar(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => SelectedCalendar)
  @nestAccessControl.UseRoles({
    resource: "SelectedCalendar",
    action: "create",
    possession: "any",
  })
  async createSelectedCalendar(
    @graphql.Args() args: CreateSelectedCalendarArgs
  ): Promise<SelectedCalendar> {
    return await this.service.createSelectedCalendar({
      ...args,
      data: {
        ...args.data,

        user: {
          connect: args.data.user,
        },
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => SelectedCalendar)
  @nestAccessControl.UseRoles({
    resource: "SelectedCalendar",
    action: "update",
    possession: "any",
  })
  async updateSelectedCalendar(
    @graphql.Args() args: UpdateSelectedCalendarArgs
  ): Promise<SelectedCalendar | null> {
    try {
      return await this.service.updateSelectedCalendar({
        ...args,
        data: {
          ...args.data,

          user: {
            connect: args.data.user,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => SelectedCalendar)
  @nestAccessControl.UseRoles({
    resource: "SelectedCalendar",
    action: "delete",
    possession: "any",
  })
  async deleteSelectedCalendar(
    @graphql.Args() args: DeleteSelectedCalendarArgs
  ): Promise<SelectedCalendar | null> {
    try {
      return await this.service.deleteSelectedCalendar(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => OrigUser, {
    nullable: true,
    name: "user",
  })
  @nestAccessControl.UseRoles({
    resource: "OrigUser",
    action: "read",
    possession: "any",
  })
  async getUser(
    @graphql.Parent() parent: SelectedCalendar
  ): Promise<OrigUser | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
